# Generated by Django 4.2.13 on 2024-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('PhoneNumber', models.BigIntegerField()),
                ('ProfilePic', models.ImageField(upload_to='static/architectures/')),
            ],
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('PhoneNumber', models.BigIntegerField()),
                ('ProfilePic', models.ImageField(upload_to='static/contractors/')),
            ],
        ),
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('PhoneNumber', models.BigIntegerField()),
                ('ProfilePic', models.ImageField(upload_to='static/designers/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('PhoneNumber', models.BigIntegerField()),
                ('ProfilePic', models.ImageField(upload_to='static/users/')),
            ],
        ),
    ]
