# Generated by Django 4.2.13 on 2024-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='static/images/works/')),
                ('TypeOfDesign', models.CharField(max_length=100)),
                ('Upload_by', models.CharField(max_length=100)),
            ],
        ),
    ]
