# Generated by Django 4.2.13 on 2024-05-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0002_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingPerson', models.CharField(max_length=100)),
                ('HomeStyle', models.CharField(max_length=100)),
                ('Plotsize', models.CharField(max_length=100)),
                ('Plotpic', models.ImageField(upload_to='static/images/bookings/')),
                ('Message', models.TextField()),
                ('RequesttoDesigner', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=200)),
                ('RequestfromDesigner', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=200)),
                ('Payment', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=200)),
                ('File', models.ImageField(default='pending', upload_to='static/images/designerdesigns/')),
                ('Price', models.IntegerField(default='pending')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.users')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.designers')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingPerson', models.CharField(max_length=100)),
                ('SquareFeet', models.IntegerField()),
                ('TimeLimit', models.CharField(max_length=100)),
                ('Plotsize', models.CharField(max_length=100)),
                ('Plan', models.ImageField(upload_to='static/images/bookings/')),
                ('Plotpic', models.ImageField(upload_to='static/images/bookings/')),
                ('Message', models.TextField()),
                ('RequesttoContractor', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=200)),
                ('RequestfromContractor', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=200)),
                ('Price', models.IntegerField(default='pending')),
                ('Contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.contractors')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingPerson', models.CharField(max_length=100)),
                ('SquareFeet', models.IntegerField()),
                ('Budget', models.IntegerField()),
                ('Plotsize', models.CharField(max_length=100)),
                ('Plotpic', models.ImageField(upload_to='static/images/bookings/')),
                ('Message', models.TextField()),
                ('RequesttoArchitect', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=200)),
                ('RequestfromArchitect', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=200)),
                ('Payment', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=200)),
                ('File', models.ImageField(default='pending', upload_to='static/images/architectdesigns/')),
                ('Price', models.IntegerField(default='pending')),
                ('Architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.architectures')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.users')),
            ],
        ),
    ]
