# Generated by Django 4.2.13 on 2024-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectbooking',
            name='PersonID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contractorbooking',
            name='PersonID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='designerbooking',
            name='PersonID',
            field=models.IntegerField(),
        ),
    ]
