# Generated by Django 4.2.13 on 2024-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0005_alter_architectbooking_personid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorbooking',
            name='Payment',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='architectbooking',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractorbooking',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='designerbooking',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
