# Generated by Django 4.2.13 on 2024-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0006_contractorbooking_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
