# Generated by Django 5.0.2 on 2024-06-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0007_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectbooking',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='contractorbooking',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='designerbooking',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
