# Generated by Django 5.0.2 on 2024-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0008_architectbooking_status_contractorbooking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectbooking',
            name='Rougharchitecture',
            field=models.ImageField(default='default', upload_to='static/images/bookings/'),
        ),
    ]
