# Generated by Django 5.0.2 on 2024-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0009_architectbooking_rougharchitecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectbooking',
            name='interest',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='designerbooking',
            name='interest',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
